config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :groups, except: [:destroy] do
    member do
      put :reset_tokens
    end
    resources :members, only: [:index, :show, :destroy]
    resources :assignments do
      resources :sessions, except: [:new, :destroy] do
        member do
          get :load_questions
        end
        resources :scores, except: [:new, :edit]
        resources :text_answers, except: [:new, :edit, :destroy]
        resources :multiple_choice_answers, except: [:new, :edit, :destroy]
        resources :matching_pair_answers, except: [:new, :edit, :destroy]
      end
    end
  end

  resources :tests do
    resources :questions, except: [:show, :new, :edit] do
      resources :multiple_choice_options, only: [:create, :update, :destroy]
      resources :matching_pairs, only: [:create, :update, :destroy]
    end
  end

  post '/join_group', to: 'members#join_group'
end

app/models/assignment.rb
# Assigning a test to a class
class Assignment < ApplicationRecord
  belongs_to :group, inverse_of: :assignments
  belongs_to :test, inverse_of: :assignments

  has_many :sessions

  validates :group, presence: true
  validates :test, presence: true
  validates :name, presence: true

  delegate :points_possible, to: :test

  def length=(value)
    if value.nil? || value[4].nil? && value[5].nil?
      self[:length] = nil
    else
      self[:length] = (value[4].nil? ? 0 : value[4]) * 60 + (value[5].nil? ? 0 : value[5])
    end
  end
end

app/controllers/assignments_controller.rb
# Controller for assignments
class AssignmentsController < ApplicationController
  load_and_authorize_resource :group
  load_and_authorize_resource through: :group

  def index
    respond_with @assignments
  end

  def show
    respond_with @assignment
  end

  def new
    respond_with @assignment
  end

  def edit
    respond_with @assignment
  end

  def create
    if !@assignment.test.nil? && @assignment.test.user != current_user
      head :bad_request
      return
    end
    if @assignment.save
      head :created, location: group_assignment_path(@assignment.group, @assignment)
    else
      render json: {error: @assignment.errors}, status: :bad_request
    end
  end

  def update
    if @assignment.update_attributes(update_params)
      head :ok
    else
      render json: {error: @assignment.errors}, status: :bad_request
    end
  end

  def destroy
    @assignment.destroy
    head :ok
  end

  private

  def create_params
    params.require(:assignment).permit(:name, :test_id, :start_date, :end_date, :length)
  end

  def update_params
    params.require(:assignment).permit(:name, :start_date, :end_date, :length)
  end
end

app/helpers/assignments_helper.rb
# Helper for AssignmentsController
module AssignmentsHelper
end

app/views/assignments/_assignment.html.erb
<div class="card">
  <div class="card-header">
    Assignment
  </div>
  <div class="card-block">
    <h4 class="card-title"><%= assignment.name %></h4>
    <p class="card-text">Unlock Date: <%= format_datetime(assignment.start_date) or 'No start date' %></p>
    <p class="card-text">Due By: <%= format_datetime(assignment.end_date) or 'No due date' %></p>
    <p class="card-text text-muted">Time Limit: <%= format_time(assignment.length) or 'No time limit' %></p>
    <%= link_to 'View', group_assignment_path(assignment.group, assignment), class: 'btn btn-primary' %>
    <% if can? :manage, assignment %>
      <%= link_to 'Edit', edit_group_assignment_path(assignment.group, assignment), class: 'btn btn-secondary' %>
    <% end %>
  </div>
  <div class="card-footer text-muted">
    Posted <%= time_ago_in_words assignment.created_at %> ago
  </div>
</div>

app/views/assignments/edit.html.erb
<h2>Edit <%= @assignment.name %></h2>
<%= form_for @assignment, url: group_assignment_path(Group.find_by(id: params[:group_id]), @assignment), remote: true do |f| %>
  <fieldset class="form-group">
    <%= f.label :name, class: 'form-control-label' %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Assignment Name' %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :start_date, class: 'form-control-label' %>
    <%= f.datetime_select :start_date, {ampm: true, include_blank: true} %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :end_date, class: 'form-control-label' %>
    <%= f.datetime_select :end_date, {ampm: true, include_blank: true} %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :length, 'Time Limit', class: 'form-control-label' %>
    <%= f.time_select :length, { include_blank: true } %>
  </fieldset>

  <%= f.submit 'Update', class: 'btn btn-primary', data: { disable_with: 'Update' } %>
<% end %>

app/views/assignments/index.html.erb
<h2>All Assignments for <%= Group.find_by(id: params[:group_id]).name %></h2>
<%= render @assignments %>

app/views/assignments/new.html.erb
<h2>Create a New Assignment</h2>
<%= form_for @assignment, url: group_assignments_path(Group.find_by(id: params[:group_id])), remote: true, form: { id: 'assignment_form' } do |f| %>
  <fieldset class="form-group">
    <%= f.label :name, class: 'form-control-label' %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Assignment Name' %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :test, class: 'form-control-label' %>
    <%= f.collection_select :test_id, current_user.tests, :id, :name, { include_blank: true }, { class: 'form-control' } %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :start_date, class: 'form-control-label' %>
    <%= f.datetime_select :start_date, {ampm: true, include_blank: true} %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :end_date, class: 'form-control-label' %>
    <%= f.datetime_select :end_date, {ampm: true, include_blank: true} %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :length, "Time Limit", class: 'form-control-label' %>
    <%= f.time_select :length, include_blank: true %>
  </fieldset>

  <%= f.submit 'Create', class: 'btn btn-primary', data: { disable_with: 'Create' } %>
<% end %>

app/views/assignments/show.html.erb
<h2><%= @assignment.name %></h2>
<h4 class="text-muted">Unlock Date: <%= format_datetime(@assignment.start_date) or 'No start date' %></h4>
<h4 class="text-muted">Due By: <%= format_datetime(@assignment.end_date) or 'No due date' %></h4>
<h4 class="text-muted">Time Limit: <%= format_time(@assignment.length) or 'No time limit' %></h4>
<%= link_to 'View Sessions', group_assignment_sessions_path(@assignment.group.id, @assignment.id), class: 'btn btn-primary btn-block' %>