config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :groups, except: [:destroy] do
    member do
      put :reset_tokens
    end
    resources :members, only: [:index, :show, :destroy]
    resources :assignments do
      resources :sessions, except: [:new, :destroy] do
        member do
          get :load_questions
        end
        resources :scores, except: [:new, :edit]
        resources :text_answers, except: [:new, :edit, :destroy]
        resources :multiple_choice_answers, except: [:new, :edit, :destroy]
        resources :matching_pair_answers, except: [:new, :edit, :destroy]
      end
    end
  end

  resources :tests do
    resources :questions, except: [:show, :new, :edit] do
      resources :multiple_choice_options, only: [:create, :update, :destroy]
      resources :matching_pairs, only: [:create, :update, :destroy]
    end
  end

  post '/join_group', to: 'members#join_group'
end

app/models/group.rb
# Organizes students and teachers into groups
class Group < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 16}
  validates :description, presence: true, length: {maximum: 2048}
  has_secure_token :student_token
  has_secure_token :teacher_token

  has_many :members
  has_many :users, through: :members
  has_many :assignments
end

app/controllers/groups_controller.rb
# Controller for groups
class GroupsController < ApplicationController
  load_and_authorize_resource

  def index
    respond_with @groups
  end

  def show
    respond_with @group
  end

  def new
    respond_with @group
  end

  def edit
    respond_with @group
  end

  def create
    if @group.save
      Member.create(group: @group, user: current_user)
      head :created, location: group_path(@group)
    else
      render json: {error: @group.errors}, status: :bad_request
    end
  end

  def update
    if @group.update_attributes(update_params)
      head :ok
    else
      render json: {error: @group.errors}, status: :bad_request
    end
  end

  def reset_tokens
    @group.regenerate_student_token
    @group.regenerate_teacher_token
    render json: {student_token: @group.student_token, teacher_token: @group.teacher_token}, status: :ok
  end

  private

  def create_params
    params.require(:group).permit(:name, :description)
  end

  def update_params
    params.require(:group).permit(:name, :description)
  end
end

app/helpers/groups_helper.rb
# Helper for GroupsController
module GroupsHelper
end

app/views/groups/_assignment.html.erb
<div class="card">
  <div class="card-header">
    Assignment
  </div>
  <div class="card-block">
    <h4 class="card-title"><%= assignment.name %></h4>
    <p class="card-text">Unlock Date: <%= format_datetime(assignment.start_date) or 'No start date' %></p>
    <p class="card-text">Due By: <%= format_datetime(assignment.end_date) or 'No due date' %></p>
    <p class="card-text text-muted">Time Limit: <%= format_time(assignment.length) or 'No time limit' %></p>
    <%= link_to 'View', group_assignment_path(assignment.group, assignment), class: 'btn btn-primary' %>
    <% if can? :manage, assignment %>
      <%= link_to 'Edit', edit_group_assignment_path(assignment.group, assignment), class: 'btn btn-secondary' %>
    <% end %>
  </div>
  <div class="card-footer text-muted">
    Posted <%= time_ago_in_words assignment.created_at %> ago
  </div>
</div>

app/views/groups/_group.html.erb
<tr>
  <td><%= group.name %></td>
  <td><%= link_to 'View', group_path(group), class: 'btn btn-primary btn-sm' %></td>
</tr>

app/views/groups/_member.html.erb
<tr>
  <td><%= member.user.name %></td>
</tr>

app/views/groups/edit.html.erb
<h2>Edit <%= @group.name %></h2>
<%= form_for @group, remote: true, form: { id: 'assignment_form' } do |f| %>
  <fieldset class="form-group">
    <%= f.label :name, class: 'form-control-label' %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Group Name' %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :description, class: 'form-control-label' %>
    <%= f.text_area :description, cols: 20, rows: 10, class: 'form-control', placeholder: 'Description' %>
  </fieldset>

  <%= f.submit 'Update', class: 'btn btn-primary', data: { disable_with: 'Update' } %>
<% end %>
<hr>
<h3>Reset Student and Teacher Token</h3>
<%= button_to 'Reset', reset_tokens_group_path, remote: true, method: :put, class: 'btn btn-danger' %>

app/views/groups/index.html.erb
<% if can? :create, Group %>
  <%= link_to new_group_path, class: 'btn btn-info float-right' do %>
    <i class="fa fa-plus"></i> Create a New Group
  <% end %>
<% end %>
<h2>My Groups</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @groups %>
  </tbody>
</table>

app/views/groups/new.html.erb
<h2>Create a New Group</h2>
<%= form_for @group, remote: true do |f| %>
  <fieldset class="form-group">
    <%= f.label :name, class: 'form-control-label' %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Group Name' %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :description, class: 'form-control-label' %>
    <%= f.text_area :description, cols: 20, rows: 10, class: 'form-control', placeholder: 'Description' %>
  </fieldset>

  <%= f.submit 'Create', class: 'btn btn-primary', data: { disable_with: 'Create' } %>
<% end %>

app/views/groups/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1><%= @group.name %></h1>
    <hr class="my-2">
    <%= simple_format @group.description, class: 'lead' %>
    <% if can? :manage, @group %>
      <%= link_to edit_group_path(@group), class: 'btn btn-secondary btn-lg' do %>
        <i class="fa fa-cog" aria-hidden="true"></i> Edit
      <% end %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-sm-12 push-md-8 col-md-4">
    <% if can? :manage, @group %>
      <% if can? :create, Assignment %>
        <%= link_to 'Assign a Test', new_group_assignment_path(@group), class: 'btn btn-secondary btn-lg btn-block', style: 'margin-bottom: 12px;' %>
      <% end %>
      <div class="card">
        <div class="card-block">
          <h4 class="card-title">Student Code</h4>
          <a class="btn btn-info btn-block btn-sm" data-toggle="collapse" href="#studentCode" aria-expanded="false" aria-controls="studentCode">
            Show Student Code
          </a>
          <div class="collapse" id="studentCode">
            <p class="bg-warning text-white text-middle text-xs-center rounded"><%= @group.student_token %></p>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-block">
          <h4 class="card-title">Teacher Code</h4>
          <a class="btn btn-danger btn-block btn-sm" data-toggle="collapse" href="#teacherCode" aria-expanded="false" aria-controls="teacherCode">
            Show Teacher Code
          </a>
          <div class="collapse" id="teacherCode">
            <p class="bg-warning text-white text-middle text-xs-center rounded"><%= @group.teacher_token %></p>
          </div>
        </div>
      </div>
    <% end %>
    <div class="card">
      <div class="card-block">
        <h4 class="card-title">Number of Members: <%= @group.members.count %></h4>
        <table class="table">
          <tbody>
            <%= render partial: 'member', collection: @group.members.last(4), as: :member or 'No Members' %>
          </tbody>
        </table>
        <%= link_to 'View All', group_members_path(@group), class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-md-8 pull-md-4">
    <%= render partial: 'assignment', collection: @group.assignments.last(10), as: :assignment or 'No assignments have been posted.' %>
    <%= link_to 'View All Assignments', group_assignments_path(@group), class: 'btn btn-secondary btn-block' %>
  </div>
</div>