config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :groups, except: [:destroy] do
    member do
      put :reset_tokens
    end
    resources :members, only: [:index, :show, :destroy]
    resources :assignments do
      resources :sessions, except: [:new, :destroy] do
        member do
          get :load_questions
        end
        resources :scores, except: [:new, :edit]
        resources :text_answers, except: [:new, :edit, :destroy]
        resources :multiple_choice_answers, except: [:new, :edit, :destroy]
        resources :matching_pair_answers, except: [:new, :edit, :destroy]
      end
    end
  end

  resources :tests do
    resources :questions, except: [:show, :new, :edit] do
      resources :multiple_choice_options, only: [:create, :update, :destroy]
      resources :matching_pairs, only: [:create, :update, :destroy]
    end
  end

  post '/join_group', to: 'members#join_group'
end

app/views/layouts/_addgroup.html.erb
<div style="margin: 1em 1em 1em 1em;">
  <h3 id="navbar_add_group_title">Join Group</h3>

  <%= form_tag({controller: 'members', action: 'join_group'}, method: 'post', remote: true, id: 'navbar_add_group') do %>
    <fieldset class="form-group">
      <%= label_tag :token, 'Token', class: 'form-control-label' %>
      <%= text_field_tag :token, '', class: 'form-control', placeholder: 'Token' %>
    </fieldset>

    <%= submit_tag 'Join Group', class: "btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-toggleable-sm navbar-inverse bg-inverse mb-2">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <%= link_to 'Testor', root_path, class: 'navbar-brand hidden-sm-down' %>
        <ul class="navbar-nav mr-auto"></ul>
        <ul class="navbar-nav">
          <% if user_signed_in? then %>
            <li class="nav-item dropdown">
              <a class="nav-link" href="#" id="addGroupDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-plus-square" aria-hidden="true"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right dropdown-width" aria-labelledby="addGroupDropdown">
                <%= render 'layouts/addgroup' %>
              </div>
            </li>
            <%= link_to 'My Groups', groups_path, class: 'nav-item nav-link' %>
            <%= link_to 'My Tests', tests_path, class: 'nav-item nav-link' %>
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>
          <% else %>
          <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>