config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :groups, except: [:destroy] do
    member do
      put :reset_tokens
    end
    resources :members, only: [:index, :show, :destroy]
    resources :assignments do
      resources :sessions, except: [:new, :destroy] do
        member do
          get :load_questions
        end
        resources :scores, except: [:new, :edit]
        resources :text_answers, except: [:new, :edit, :destroy]
        resources :multiple_choice_answers, except: [:new, :edit, :destroy]
        resources :matching_pair_answers, except: [:new, :edit, :destroy]
      end
    end
  end

  resources :tests do
    resources :questions, except: [:show, :new, :edit] do
      resources :multiple_choice_options, only: [:create, :update, :destroy]
      resources :matching_pairs, only: [:create, :update, :destroy]
    end
  end

  post '/join_group', to: 'members#join_group'
end

app/models/member.rb
# References a user for a group
class Member < ApplicationRecord
  belongs_to :group, inverse_of: :members
  belongs_to :user, inverse_of: :members

  validates :group, presence: true

  validates :user, presence: true
  validates :user, uniqueness: {scope: :group}
end

app/controllers/members_controller.rb
# Controller for members, also handles joining group by token
class MembersController < ApplicationController
  load_and_authorize_resource :group, except: :join_group
  load_and_authorize_resource through: :group, except: :join_group
  authorize_resource only: :join_group

  def index
    respond_with @members
  end

  def show
    respond_with @member
  end

  def join_group
    if current_user.teacher?
      @group = Group.find_by(teacher_token: params[:token])
    elsif current_user.student?
      @group = Group.find_by(student_token: params[:token])
    end

    if @group.nil?
      head :bad_request
      return
    end
    if Member.find_by(group: @group, user: current_user)
      head :bad_request
      return
    end

    Member.create(group: @group, user: current_user)
    head :created, location: group_path(@group)
  end

  def destroy
    @member.destroy
    head :ok
  end
end

app/helpers/members_helper.rb
# Helper for MembersController
module MembersHelper
end

app/views/members/_member.html.erb
<tr>
  <td><%= member.user.name %></td>
  <td><%= role_name member.user.role %></td>
  <td><%= link_to 'View', group_member_path(member.group, member), class: 'btn btn-primary' %></td>
  <% if can? :destroy, member %>
    <td><%= button_to 'Kick', {event_id: member.group.id, id: member.id, controller: :members, action: :destroy}, remote: true, method: :delete, class: 'btn btn-danger', id: 'kick_' + member.id.to_s %></td>
  <% end %>
</tr>

app/views/members/index.html.erb
<% group = Group.find_by(id: params[:group_id]) %>
<h2>All Members in <%= group.name %></h2>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th></th>
      <% if can? :destroy, Member %>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'member', collection: group.members, as: :member %>
  </tbody>
</table>

app/views/members/show.html.erb
<h2><%= @member.user.name %></h2>
<h4 class="text-muted"><%= role_name @member.user.role %></h4>